nodeLinker: pnp
enableGlobalCache: false

pnpMode: loose
enableHardenedMode: false

packageExtensions:
  "firebase@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/auth": "*"
      "@firebase/firestore": "*"
      "@firebase/database": "*"
      "@firebase/functions": "*"
  "@firebase/app@*":
    peerDependencies:
      "@firebase/app-types": "*"
  "@firebase/auth@*":
    peerDependencies:
      "@firebase/app-types": "*"
  "@firebase/database@*":
    peerDependencies:
      "@firebase/app-types": "*"
      "@firebase/app": "*"
  "@firebase/firestore@*":
    peerDependencies:
      "@firebase/app-types": "*"
  "@firebase/functions@*":
    peerDependencies:
      "@firebase/app-types": "*"
  "@testing-library/react@*":
    peerDependencies:
      "react-dom": "*"
      "react": "*"
    peerDependenciesMeta:
      "react-dom":
        optional: true
      "react":
        optional: true
  "debug@*":
    peerDependencies:
      "supports-color": "*"
    peerDependenciesMeta:
      "supports-color":
        optional: true
  vite@*:
    peerDependencies:
      "@types/node": "*"

# Enable zero-installs for better performance and offline capability
cacheFolder: .yarn/cache
checksumBehavior: update

# Enable pnp for TypeScript (IDE support)
pnpEnableEsmLoader: true
pnpEnableInlining: true
