import { NBAPlayer } from '../types';

/**
 * Mock NBA player data
 * This data is used for development and testing purposes
 */
export const mockPlayers: NBAPlayer[] = [
  // Western Conference
  // Los Angeles Lakers
  {
    id: 'lebron-james',
    firstName: 'LeBron',
    lastName: 'James',
    fullName: 'LeBron James',
    team: 'LAL',
    position: ['SF', 'PF'],
    height: '6-9',
    weight: 250,
    jerseyNumber: '23',
    active: true,
    rookieYear: 2003,
    stats: {
      points: 25.7,
      rebounds: 7.3,
      assists: 8.3,
      steals: 1.3,
      blocks: 0.5,
      threePointersMade: 2.1,
      fieldGoalPercentage: 0.54,
      freeThrowPercentage: 0.75,
      gamesPlayed: 71,
      minutesPerGame: 35.5,
      turnovers: 3.1,
      personalFouls: 1.6,
    },
  },
  {
    id: 'anthony-davis',
    firstName: 'Anthony',
    lastName: 'Davis',
    fullName: 'Anthony Davis',
    team: 'LAL',
    position: ['PF', 'C'],
    height: '6-10',
    weight: 253,
    jerseyNumber: '3',
    active: true,
    rookieYear: 2012,
    stats: {
      points: 25.9,
      rebounds: 12.5,
      assists: 3.5,
      steals: 1.1,
      blocks: 2.3,
      threePointersMade: 0.4,
      fieldGoalPercentage: 0.55,
      freeThrowPercentage: 0.81,
      gamesPlayed: 76,
      minutesPerGame: 36.4,
      turnovers: 2.0,
      personalFouls: 2.4,
    },
  },
  {
    id: 'austin-reaves',
    firstName: 'Austin',
    lastName: 'Reaves',
    fullName: 'Austin Reaves',
    team: 'LAL',
    position: 'SG',
    height: '6-5',
    weight: 206,
    jerseyNumber: '15',
    active: true,
    rookieYear: 2021,
    stats: {
      points: 16.0,
      rebounds: 4.1,
      assists: 5.5,
      steals: 0.9,
      blocks: 0.3,
      threePointersMade: 1.7,
      fieldGoalPercentage: 0.48,
      freeThrowPercentage: 0.87,
      gamesPlayed: 80,
      minutesPerGame: 32.8,
      turnovers: 1.9,
      personalFouls: 1.8,
    },
  },
  // Golden State Warriors
  {
    id: 'stephen-curry',
    firstName: 'Stephen',
    lastName: 'Curry',
    fullName: 'Stephen Curry',
    team: 'GSW',
    position: 'PG',
    height: '6-2',
    weight: 185,
    jerseyNumber: '30',
    active: true,
    rookieYear: 2009,
    stats: {
      points: 26.4,
      rebounds: 4.5,
      assists: 6.7,
      steals: 0.9,
      blocks: 0.4,
      threePointersMade: 4.9,
      fieldGoalPercentage: 0.45,
      freeThrowPercentage: 0.92,
      gamesPlayed: 74,
      minutesPerGame: 33.5,
      turnovers: 3.1,
      personalFouls: 1.8,
    },
  },
  {
    id: 'draymond-green',
    firstName: 'Draymond',
    lastName: 'Green',
    fullName: 'Draymond Green',
    team: 'GSW',
    position: ['PF', 'C'],
    height: '6-6',
    weight: 230,
    jerseyNumber: '23',
    active: true,
    rookieYear: 2012,
    stats: {
      points: 8.8,
      rebounds: 7.6,
      assists: 6.8,
      steals: 1.2,
      blocks: 0.8,
      threePointersMade: 0.7,
      fieldGoalPercentage: 0.52,
      freeThrowPercentage: 0.7,
      gamesPlayed: 73,
      minutesPerGame: 31.5,
      turnovers: 2.8,
      personalFouls: 3.4,
    },
  },
  // Denver Nuggets
  {
    id: 'nikola-jokic',
    firstName: 'Nikola',
    lastName: 'Jokić',
    fullName: 'Nikola Jokić',
    team: 'DEN',
    position: 'C',
    height: '6-11',
    weight: 284,
    jerseyNumber: '15',
    active: true,
    rookieYear: 2015,
    stats: {
      points: 26.3,
      rebounds: 12.2,
      assists: 9.0,
      steals: 1.3,
      blocks: 0.7,
      threePointersMade: 1.1,
      fieldGoalPercentage: 0.58,
      freeThrowPercentage: 0.82,
      gamesPlayed: 79,
      minutesPerGame: 34.5,
      turnovers: 3.4,
      personalFouls: 2.5,
    },
  },
  {
    id: 'jamal-murray',
    firstName: 'Jamal',
    lastName: 'Murray',
    fullName: 'Jamal Murray',
    team: 'DEN',
    position: 'PG',
    height: '6-4',
    weight: 215,
    jerseyNumber: '27',
    active: true,
    rookieYear: 2016,
    stats: {
      points: 20.3,
      rebounds: 4.0,
      assists: 6.2,
      steals: 1.0,
      blocks: 0.3,
      threePointersMade: 2.5,
      fieldGoalPercentage: 0.45,
      freeThrowPercentage: 0.83,
      gamesPlayed: 70,
      minutesPerGame: 32.8,
      turnovers: 2.2,
      personalFouls: 1.7,
    },
  },
  // Phoenix Suns
  {
    id: 'kevin-durant',
    firstName: 'Kevin',
    lastName: 'Durant',
    fullName: 'Kevin Durant',
    team: 'PHX',
    position: ['SF', 'PF'],
    height: '6-11',
    weight: 240,
    jerseyNumber: '35',
    active: true,
    rookieYear: 2007,
    stats: {
      points: 28.3,
      rebounds: 6.7,
      assists: 5.0,
      steals: 0.7,
      blocks: 1.2,
      threePointersMade: 2.3,
      fieldGoalPercentage: 0.53,
      freeThrowPercentage: 0.89,
      gamesPlayed: 65,
      minutesPerGame: 35.5,
      turnovers: 3.3,
      personalFouls: 1.8,
    },
  },
  {
    id: 'devin-booker',
    firstName: 'Devin',
    lastName: 'Booker',
    fullName: 'Devin Booker',
    team: 'PHX',
    position: 'SG',
    height: '6-5',
    weight: 206,
    jerseyNumber: '1',
    active: true,
    rookieYear: 2015,
    stats: {
      points: 27.1,
      rebounds: 4.5,
      assists: 6.0,
      steals: 1.0,
      blocks: 0.3,
      threePointersMade: 2.2,
      fieldGoalPercentage: 0.49,
      freeThrowPercentage: 0.85,
      gamesPlayed: 72,
      minutesPerGame: 36.2,
      turnovers: 2.7,
      personalFouls: 2.4,
    },
  },

  // Eastern Conference
  // Boston Celtics
  {
    id: 'jayson-tatum',
    firstName: 'Jayson',
    lastName: 'Tatum',
    fullName: 'Jayson Tatum',
    team: 'BOS',
    position: ['SF', 'PF'],
    height: '6-8',
    weight: 210,
    jerseyNumber: '0',
    active: true,
    rookieYear: 2017,
    stats: {
      points: 27.6,
      rebounds: 8.6,
      assists: 4.8,
      steals: 1.1,
      blocks: 0.7,
      threePointersMade: 3.0,
      fieldGoalPercentage: 0.46,
      freeThrowPercentage: 0.85,
      gamesPlayed: 80,
      minutesPerGame: 36.9,
      turnovers: 2.9,
      personalFouls: 2.1,
    },
  },
  {
    id: 'jaylen-brown',
    firstName: 'Jaylen',
    lastName: 'Brown',
    fullName: 'Jaylen Brown',
    team: 'BOS',
    position: ['SG', 'SF'],
    height: '6-6',
    weight: 223,
    jerseyNumber: '7',
    active: true,
    rookieYear: 2016,
    stats: {
      points: 26.6,
      rebounds: 6.5,
      assists: 3.5,
      steals: 1.2,
      blocks: 0.5,
      threePointersMade: 2.4,
      fieldGoalPercentage: 0.49,
      freeThrowPercentage: 0.71,
      gamesPlayed: 76,
      minutesPerGame: 35.4,
      turnovers: 2.7,
      personalFouls: 2.5,
    },
  },
  // Milwaukee Bucks
  {
    id: 'giannis-antetokounmpo',
    firstName: 'Giannis',
    lastName: 'Antetokounmpo',
    fullName: 'Giannis Antetokounmpo',
    team: 'MIL',
    position: ['PF', 'C'],
    height: '6-11',
    weight: 242,
    jerseyNumber: '34',
    active: true,
    rookieYear: 2013,
    stats: {
      points: 30.4,
      rebounds: 11.5,
      assists: 5.7,
      steals: 0.9,
      blocks: 1.2,
      threePointersMade: 0.7,
      fieldGoalPercentage: 0.56,
      freeThrowPercentage: 0.65,
      gamesPlayed: 73,
      minutesPerGame: 35.2,
      turnovers: 3.9,
      personalFouls: 3.1,
    },
  },
  {
    id: 'damian-lillard',
    firstName: 'Damian',
    lastName: 'Lillard',
    fullName: 'Damian Lillard',
    team: 'MIL',
    position: 'PG',
    height: '6-2',
    weight: 195,
    jerseyNumber: '0',
    active: true,
    rookieYear: 2012,
    stats: {
      points: 24.7,
      rebounds: 4.2,
      assists: 7.3,
      steals: 1.0,
      blocks: 0.3,
      threePointersMade: 3.9,
      fieldGoalPercentage: 0.43,
      freeThrowPercentage: 0.92,
      gamesPlayed: 68,
      minutesPerGame: 35.6,
      turnovers: 3.1,
      personalFouls: 1.8,
    },
  },
  // Philadelphia 76ers
  {
    id: 'joel-embiid',
    firstName: 'Joel',
    lastName: 'Embiid',
    fullName: 'Joel Embiid',
    team: 'PHI',
    position: 'C',
    height: '7-0',
    weight: 280,
    jerseyNumber: '21',
    active: true,
    rookieYear: 2014,
    stats: {
      points: 34.7,
      rebounds: 11.0,
      assists: 4.1,
      steals: 1.0,
      blocks: 1.7,
      threePointersMade: 1.0,
      fieldGoalPercentage: 0.53,
      freeThrowPercentage: 0.86,
      gamesPlayed: 66,
      minutesPerGame: 34.6,
      turnovers: 3.4,
      personalFouls: 2.9,
    },
  },
  {
    id: 'tyrese-maxey',
    firstName: 'Tyrese',
    lastName: 'Maxey',
    fullName: 'Tyrese Maxey',
    team: 'PHI',
    position: 'PG',
    height: '6-2',
    weight: 200,
    jerseyNumber: '0',
    active: true,
    rookieYear: 2020,
    stats: {
      points: 25.9,
      rebounds: 3.7,
      assists: 6.2,
      steals: 1.0,
      blocks: 0.5,
      threePointersMade: 3.4,
      fieldGoalPercentage: 0.45,
      freeThrowPercentage: 0.85,
      gamesPlayed: 70,
      minutesPerGame: 37.5,
      turnovers: 2.1,
      personalFouls: 1.7,
    },
  },
  // New York Knicks
  {
    id: 'jalen-brunson',
    firstName: 'Jalen',
    lastName: 'Brunson',
    fullName: 'Jalen Brunson',
    team: 'NYK',
    position: 'PG',
    height: '6-2',
    weight: 190,
    jerseyNumber: '11',
    active: true,
    rookieYear: 2018,
    stats: {
      points: 28.7,
      rebounds: 3.6,
      assists: 6.7,
      steals: 0.9,
      blocks: 0.2,
      threePointersMade: 2.0,
      fieldGoalPercentage: 0.48,
      freeThrowPercentage: 0.85,
      gamesPlayed: 77,
      minutesPerGame: 35.4,
      turnovers: 2.4,
      personalFouls: 2.2,
    },
  },
  {
    id: 'julius-randle',
    firstName: 'Julius',
    lastName: 'Randle',
    fullName: 'Julius Randle',
    team: 'NYK',
    position: 'PF',
    height: '6-8',
    weight: 250,
    jerseyNumber: '30',
    active: true,
    rookieYear: 2014,
    stats: {
      points: 21.4,
      rebounds: 9.2,
      assists: 4.6,
      steals: 0.5,
      blocks: 0.3,
      threePointersMade: 1.9,
      fieldGoalPercentage: 0.47,
      freeThrowPercentage: 0.76,
      gamesPlayed: 70,
      minutesPerGame: 33.4,
      turnovers: 3.7,
      personalFouls: 3.0,
    },
  },
  // Miami Heat
  {
    id: 'jimmy-butler',
    firstName: 'Jimmy',
    lastName: 'Butler',
    fullName: 'Jimmy Butler',
    team: 'MIA',
    position: ['SF', 'SG'],
    height: '6-7',
    weight: 230,
    jerseyNumber: '22',
    active: true,
    rookieYear: 2011,
    stats: {
      points: 20.8,
      rebounds: 5.5,
      assists: 5.0,
      steals: 1.3,
      blocks: 0.5,
      threePointersMade: 0.5,
      fieldGoalPercentage: 0.49,
      freeThrowPercentage: 0.85,
      gamesPlayed: 60,
      minutesPerGame: 33.5,
      turnovers: 1.9,
      personalFouls: 1.7,
    },
  },
  {
    id: 'bam-adebayo',
    firstName: 'Bam',
    lastName: 'Adebayo',
    fullName: 'Bam Adebayo',
    team: 'MIA',
    position: 'C',
    height: '6-9',
    weight: 255,
    jerseyNumber: '13',
    active: true,
    rookieYear: 2017,
    stats: {
      points: 19.3,
      rebounds: 10.4,
      assists: 3.9,
      steals: 1.1,
      blocks: 0.9,
      threePointersMade: 0.0,
      fieldGoalPercentage: 0.52,
      freeThrowPercentage: 0.75,
      gamesPlayed: 75,
      minutesPerGame: 34.0,
      turnovers: 2.5,
      personalFouls: 2.8,
    },
  },
];
