import { NBAGamePerformance } from '../types';

/**
 * Mock NBA game performance data
 * This data is used for development and testing purposes
 */
export const mockPerformances: NBAGamePerformance[] = [
  // Lakers vs Celtics on Christmas
  {
    gameId: 'game-lal-bos-20231225',
    playerId: 'lebron-james',
    minutes: 38,
    points: 32,
    rebounds: 11,
    assists: 7,
    steals: 2,
    blocks: 1,
    turnovers: 3,
    fieldGoalsMade: 12,
    fieldGoalsAttempted: 21,
    threePointersMade: 3,
    threePointersAttempted: 7,
    freeThrowsMade: 5,
    freeThrowsAttempted: 6,
    personalFouls: 2,
  },
  {
    gameId: 'game-lal-bos-20231225',
    playerId: 'anthony-davis',
    minutes: 40,
    points: 28,
    rebounds: 15,
    assists: 4,
    steals: 1,
    blocks: 3,
    turnovers: 2,
    fieldGoalsMade: 11,
    fieldGoalsAttempted: 17,
    threePointersMade: 0,
    threePointersAttempted: 1,
    freeThrowsMade: 6,
    freeThrowsAttempted: 7,
    personalFouls: 3,
  },
  {
    gameId: 'game-lal-bos-20231225',
    playerId: 'austin-reaves',
    minutes: 35,
    points: 18,
    rebounds: 4,
    assists: 6,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fieldGoalsMade: 6,
    fieldGoalsAttempted: 12,
    threePointersMade: 3,
    threePointersAttempted: 6,
    freeThrowsMade: 3,
    freeThrowsAttempted: 3,
    personalFouls: 2,
  },
  {
    gameId: 'game-lal-bos-20231225',
    playerId: 'jayson-tatum',
    minutes: 40,
    points: 30,
    rebounds: 8,
    assists: 6,
    steals: 1,
    blocks: 1,
    turnovers: 2,
    fieldGoalsMade: 11,
    fieldGoalsAttempted: 24,
    threePointersMade: 4,
    threePointersAttempted: 9,
    freeThrowsMade: 4,
    freeThrowsAttempted: 5,
    personalFouls: 3,
  },
  {
    gameId: 'game-lal-bos-20231225',
    playerId: 'jaylen-brown',
    minutes: 38,
    points: 25,
    rebounds: 7,
    assists: 4,
    steals: 2,
    blocks: 0,
    turnovers: 3,
    fieldGoalsMade: 10,
    fieldGoalsAttempted: 20,
    threePointersMade: 2,
    threePointersAttempted: 6,
    freeThrowsMade: 3,
    freeThrowsAttempted: 4,
    personalFouls: 4,
  },

  // Warriors vs Nuggets on Christmas
  {
    gameId: 'game-gsw-den-20231225',
    playerId: 'stephen-curry',
    minutes: 37,
    points: 36,
    rebounds: 5,
    assists: 8,
    steals: 1,
    blocks: 0,
    turnovers: 3,
    fieldGoalsMade: 12,
    fieldGoalsAttempted: 25,
    threePointersMade: 8,
    threePointersAttempted: 15,
    freeThrowsMade: 4,
    freeThrowsAttempted: 4,
    personalFouls: 2,
  },
  {
    gameId: 'game-gsw-den-20231225',
    playerId: 'draymond-green',
    minutes: 32,
    points: 10,
    rebounds: 9,
    assists: 11,
    steals: 2,
    blocks: 1,
    turnovers: 2,
    fieldGoalsMade: 4,
    fieldGoalsAttempted: 7,
    threePointersMade: 1,
    threePointersAttempted: 3,
    freeThrowsMade: 1,
    freeThrowsAttempted: 2,
    personalFouls: 4,
  },
  {
    gameId: 'game-gsw-den-20231225',
    playerId: 'nikola-jokic',
    minutes: 36,
    points: 32,
    rebounds: 15,
    assists: 10,
    steals: 1,
    blocks: 1,
    turnovers: 3,
    fieldGoalsMade: 12,
    fieldGoalsAttempted: 19,
    threePointersMade: 2,
    threePointersAttempted: 4,
    freeThrowsMade: 6,
    freeThrowsAttempted: 7,
    personalFouls: 3,
  },
  {
    gameId: 'game-gsw-den-20231225',
    playerId: 'jamal-murray',
    minutes: 35,
    points: 24,
    rebounds: 3,
    assists: 8,
    steals: 2,
    blocks: 0,
    turnovers: 2,
    fieldGoalsMade: 9,
    fieldGoalsAttempted: 18,
    threePointersMade: 4,
    threePointersAttempted: 9,
    freeThrowsMade: 2,
    freeThrowsAttempted: 2,
    personalFouls: 2,
  },

  // Bucks vs 76ers on Christmas
  {
    gameId: 'game-mil-phi-20231225',
    playerId: 'giannis-antetokounmpo',
    minutes: 36,
    points: 34,
    rebounds: 14,
    assists: 7,
    steals: 0,
    blocks: 2,
    turnovers: 5,
    fieldGoalsMade: 13,
    fieldGoalsAttempted: 21,
    threePointersMade: 1,
    threePointersAttempted: 3,
    freeThrowsMade: 7,
    freeThrowsAttempted: 12,
    personalFouls: 3,
  },
  {
    gameId: 'game-mil-phi-20231225',
    playerId: 'damian-lillard',
    minutes: 38,
    points: 26,
    rebounds: 4,
    assists: 10,
    steals: 1,
    blocks: 0,
    turnovers: 2,
    fieldGoalsMade: 8,
    fieldGoalsAttempted: 18,
    threePointersMade: 5,
    threePointersAttempted: 11,
    freeThrowsMade: 5,
    freeThrowsAttempted: 5,
    personalFouls: 2,
  },
  {
    gameId: 'game-mil-phi-20231225',
    playerId: 'joel-embiid',
    minutes: 37,
    points: 36,
    rebounds: 12,
    assists: 5,
    steals: 2,
    blocks: 3,
    turnovers: 4,
    fieldGoalsMade: 13,
    fieldGoalsAttempted: 24,
    threePointersMade: 1,
    threePointersAttempted: 4,
    freeThrowsMade: 9,
    freeThrowsAttempted: 10,
    personalFouls: 3,
  },
  {
    gameId: 'game-mil-phi-20231225',
    playerId: 'tyrese-maxey',
    minutes: 40,
    points: 24,
    rebounds: 3,
    assists: 6,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fieldGoalsMade: 9,
    fieldGoalsAttempted: 19,
    threePointersMade: 3,
    threePointersAttempted: 9,
    freeThrowsMade: 3,
    freeThrowsAttempted: 4,
    personalFouls: 1,
  },

  // Suns vs Lakers on New Year's Eve
  {
    gameId: 'game-pho-lal-20231231',
    playerId: 'kevin-durant',
    minutes: 39,
    points: 35,
    rebounds: 7,
    assists: 5,
    steals: 1,
    blocks: 2,
    turnovers: 3,
    fieldGoalsMade: 13,
    fieldGoalsAttempted: 22,
    threePointersMade: 3,
    threePointersAttempted: 6,
    freeThrowsMade: 6,
    freeThrowsAttempted: 6,
    personalFouls: 2,
  },
  {
    gameId: 'game-pho-lal-20231231',
    playerId: 'devin-booker',
    minutes: 38,
    points: 28,
    rebounds: 5,
    assists: 8,
    steals: 2,
    blocks: 0,
    turnovers: 4,
    fieldGoalsMade: 11,
    fieldGoalsAttempted: 23,
    threePointersMade: 3,
    threePointersAttempted: 8,
    freeThrowsMade: 3,
    freeThrowsAttempted: 4,
    personalFouls: 3,
  },
  {
    gameId: 'game-pho-lal-20231231',
    playerId: 'lebron-james',
    minutes: 37,
    points: 30,
    rebounds: 9,
    assists: 12,
    steals: 1,
    blocks: 0,
    turnovers: 4,
    fieldGoalsMade: 11,
    fieldGoalsAttempted: 20,
    threePointersMade: 2,
    threePointersAttempted: 6,
    freeThrowsMade: 6,
    freeThrowsAttempted: 8,
    personalFouls: 1,
  },
  {
    gameId: 'game-pho-lal-20231231',
    playerId: 'anthony-davis',
    minutes: 40,
    points: 32,
    rebounds: 15,
    assists: 3,
    steals: 1,
    blocks: 4,
    turnovers: 2,
    fieldGoalsMade: 13,
    fieldGoalsAttempted: 21,
    threePointersMade: 0,
    threePointersAttempted: 0,
    freeThrowsMade: 6,
    freeThrowsAttempted: 9,
    personalFouls: 4,
  },

  // Lakers vs Warriors matchup
  {
    gameId: 'game-lal-gsw-20240115',
    playerId: 'lebron-james',
    minutes: 39,
    points: 36,
    rebounds: 12,
    assists: 8,
    steals: 1,
    blocks: 1,
    turnovers: 3,
    fieldGoalsMade: 14,
    fieldGoalsAttempted: 25,
    threePointersMade: 3,
    threePointersAttempted: 7,
    freeThrowsMade: 5,
    freeThrowsAttempted: 7,
    personalFouls: 2,
  },
  {
    gameId: 'game-lal-gsw-20240115',
    playerId: 'anthony-davis',
    minutes: 41,
    points: 35,
    rebounds: 17,
    assists: 4,
    steals: 2,
    blocks: 5,
    turnovers: 1,
    fieldGoalsMade: 14,
    fieldGoalsAttempted: 22,
    threePointersMade: 1,
    threePointersAttempted: 1,
    freeThrowsMade: 6,
    freeThrowsAttempted: 8,
    personalFouls: 3,
  },
  {
    gameId: 'game-lal-gsw-20240115',
    playerId: 'stephen-curry',
    minutes: 36,
    points: 40,
    rebounds: 6,
    assists: 9,
    steals: 3,
    blocks: 0,
    turnovers: 4,
    fieldGoalsMade: 14,
    fieldGoalsAttempted: 28,
    threePointersMade: 9,
    threePointersAttempted: 17,
    freeThrowsMade: 3,
    freeThrowsAttempted: 3,
    personalFouls: 2,
  },
  {
    gameId: 'game-lal-gsw-20240115',
    playerId: 'draymond-green',
    minutes: 32,
    points: 8,
    rebounds: 11,
    assists: 9,
    steals: 2,
    blocks: 2,
    turnovers: 3,
    fieldGoalsMade: 3,
    fieldGoalsAttempted: 7,
    threePointersMade: 0,
    threePointersAttempted: 2,
    freeThrowsMade: 2,
    freeThrowsAttempted: 4,
    personalFouls: 5,
  },
];
